<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Modulos\" />
    <Folder Include="Modulos\Fabricantes\" />
    <Folder Include="Modulos\Fabricantes\Apresentacao\" />
    <Folder Include="Modulos\Fabricantes\Dominio\" />
    <Folder Include="Modulos\Fabricantes\Infraestrutura\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
